name: Coverity Scan

on:
  push:
    branches: [ main ]

jobs:
  coverity-scan:
    runs-on: ubuntu-latest
    env:
      COVERITY_PROJECT: 230290127_DVWATest
      COVERITY_TOKEN: EH15aKgDxzgo4sRfYoGgNQ
      COVERITY_EMAIL: theynsk.2244@gmail.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Coverity Analysis CLI
        run: |
          curl -L \
            "https://scan.coverity.com/download/cxx/linux64?project=${COVERITY_PROJECT}&token=${COVERITY_TOKEN}" \
            -o coverity.tgz
          mkdir covtool
          tar xzf coverity.tgz --strip-components=1 -C covtool

      - name: Run Buildless Capture & Analyze
        run: |
          covtool/bin/cov-capture --dir cov-int --language php --source-dir .
          covtool/bin/cov-analyze --dir cov-int --all
          covtool/bin/cov-format-errors --dir cov-int --json-output cov-results.json

      - name: Package results
        run: zip -r cov-int.zip cov-int

      - name: Upload to Coverity Scan
        run: |
          curl -X POST "https://scan.coverity.com/builds?project=${COVERITY_PROJECT}" \
            -F token="${COVERITY_TOKEN}" \
            -F email="${COVERITY_EMAIL}" \
            -F file=@cov-int.zip

      - name: Confirm submission
        run: echo "Build submitted – check Coverity dashboard."
